name: "Ejemplo"
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Despliega el típico "Hola, mundo"
        shell: bash
        run: |
          echo "Hello, World!"
          echo "Nuevo workflow"
